version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${PROD_POSTGRES_USER}
      POSTGRES_DB: ${PROD_POSTGRES_DB}
      POSTGRES_PASSWORD: ${PROD_POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: postgres-db

volumes:
  postgres: 
